name: Testes Manuais

on:
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependências
        run: yarn install

      - name: Instalar navegadores do Playwright
        run: npx playwright install --with-deps

      - name: Executar testes E2E
        run: yarn e2e
